name: "ssq"  #"选择训练数据"
windows_size: '5'  #"训练窗口大小,如有多个，用'，'隔开"
red_epochs: 100  #"红球训练轮数"
blue_epochs: 1  #"蓝球训练轮数"
batch_size: 32  #"集合数量"
predict_pro: 0  #"更新batch_size"
epochs: 1  #"训练轮数(红蓝球交叉训练"
cq: 0  #"是否使用出球顺序，0：不使用（即按从小到大排序），1：使用"
download_data: 1  #"是否下载数据"
hidden_size: 512  #"hidden_size"
num_layers: 6  #"num_layers"
num_heads: 8  #"num_heads"
tensorboard: 0  #"tensorboard switch"
num_workers: 0  #"num_workers switch"
top_k: 10  #"top_k switch"
model: 'Transformer'  #"model name"
lr: 0.01  #"learning rate"
plus_mode: 0  #"plus mode"
ext_times: 1000  #"ext_times"
init: 0  #"init"
train_mode: 0  #"0:  mormal, 1:  new trainning, 2:  best test model, 3:  best loss model"
split_time: 2021351  #"tranning data split time, greater than 0, will saving best test model"
save_best_loss: 0  #"save best loss model"
output_dir: /nuwa/save/ssq/